### ISSUE TITLE
list isn’t updated unless watchers is a tuple

### ISSUE THREAD

**Issue by skurfer** [collective/collective.watcherlist#4]
In `toggle_watching()`, if `self.watchers` is a list, it never gets updated.

The local `watchers` variable is updated, but the new value is never used to set `self.watchers` unless it was a tuple.

If the local `watchers` and `self.watchers` were referring to the same mutable object, it would work, but they aren't:

```python
>>> watchers is self.watchers
False
```

**Comment by mauritsvanrees** [comment]
When I look at the code, and `self.watchers` is not a tuple but a list, then it seems to me like `watchers is self.watchers` should be True. So it is strange that you see this is not the case.

I think the current code would work if self.watchers is a PersistentList instead of a standard Python list. But your fix looks good.
The Travis tests are failing during the buildout phase, which has nothing to do with this pull request. I will have a look at the tests first and then revisit this.
