### ISSUE TITLE
"immediate" param to mail_host.send prevent usage of mailqueue

### ISSUE THREAD

**Issue by keul** [collective/collective.watcherlist#8]
See https://github.com/collective/collective.watcherlist/blob/14f8883face8371293685c76df50468c9c17db40/collective/watcherlist/mailer.py#L56

As we are providing the `immediate` attribute, mail host queue (if enabled) is not used. In the case mail server is temporary unavailable the whole Poi became unresponsive.

There's a reason for that?

**Comment by mauritsvanrees** [comment]
I think at the time I made this the 'immediate' keyword was quite new. Or I wanted to be certain that the mails were really sent before doing anything else in a transaction.

I'd say it would be fine to change the default [here](https://github.com/collective/collective.watcherlist/blob/0161e9dbc2f42bdfa0653c917e2b04d8e06cbe9c/collective/watcherlist/mailer.py#L12).

And maybe in [watchers.py](https://github.com/collective/collective.watcherlist/blob/0161e9dbc2f42bdfa0653c917e2b04d8e06cbe9c/collective/watcherlist/watchers.py#L206) check if 'immediate' is in the keyword arguments and then pass it to [simple_send_mail](https://github.com/collective/collective.watcherlist/blob/0161e9dbc2f42bdfa0653c917e2b04d8e06cbe9c/collective/watcherlist/watchers.py#L237).

Are you up for a pull request?

**Comment by keul** [comment]
@mauritsvanrees yes I can work on this. Thanks!

**Comment by mauritsvanrees** [comment]
Thinking about this again, there is a different reason that I did it like this: I send the mail immediately, because then I can catch any errors and continue with the transaction anyway.

For example in the case of Products.Poi, if I add a response to an issue, and there is a problem sending the mail to one of the watchers, then I want to add this response anyway. I don't want to get a traceback.

Without 'immediate' I am not completely sure what would happen. But from looking at the code in `Products.MailHost` and `zope.sendmail`, it should be fine: the message sending happens in the [`tpc_finish`](http://zodb.readthedocs.io/en/latest/transactions.html#tpc-finish) part of the transaction, which is after the transaction has completed.

So: it should still be okay to set `immediate=False` as default, though I would like to test it a bit more to be sure.

**Comment by keul** [comment]
@mauritsvanrees IIRC when I checked the code I saw that without "immediate" there's a check on the queue state (active or not) when sending the email so I think is still safe.

**Comment by mauritsvanrees** [comment]
Fixed.

**Comment by mauritsvanrees** [comment]
I have released the fix in release 3.0.
